'use client';

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/providers/auth-provider';
import EstimatesTable from '@/components/admin/estimates-table';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { getEstimates } from '@/lib/firebase';
import { LayoutDashboard, ClipboardList, Home, Paintbrush, Loader2 } from 'lucide-react';

export default function AdminPage() {
  const { user, loading, isAdmin } = useAuth();
  const router = useRouter();
  const [stats, setStats] = useState({
    total: 0,
    interior: 0,
    exterior: 0,
  });
  const [isStatsLoading, setIsStatsLoading] = useState(true);

  useEffect(() => {
    if (!loading && !user) {
      router.push('/login');
    }
  }, [user, loading, router]);

  useEffect(() => {
    if (isAdmin) {
      const fetchStats = async () => {
        try {
          const estimates = await getEstimates();
          const total = estimates.length;
          const interior = estimates.filter((e: any) => e.options?.typeOfWork?.includes('Interior Painting')).length;
          const exterior = estimates.filter((e: any) => e.options?.typeOfWork?.includes('Exterior Painting')).length;
          setStats({ total, interior, exterior });
        } catch (error) {
          console.error("Error fetching stats:", error);
        } finally {
          setIsStatsLoading(false);
        }
      };
      fetchStats();
    }
  }, [isAdmin]);

  if (loading) {
    return (
      <div className="flex h-[60vh] items-center justify-center">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
      </div>
    );
  }

  if (!isAdmin) {
    return (
      <div className="container mx-auto py-20 text-center">
        <Card className="max-w-md mx-auto">
          <CardContent className="pt-6">
            <h1 className="text-2xl font-bold text-destructive mb-2">Access Denied</h1>
            <p className="text-muted-foreground">You are not authorized to view the admin dashboard.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-10 px-4 space-y-8">
      <div className="flex items-center gap-3">
        <div className="p-2 bg-primary/10 rounded-lg">
          <LayoutDashboard className="h-6 w-6 text-primary" />
        </div>
        <h1 className="text-3xl font-bold tracking-tight">Admin Dashboard</h1>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card className="shadow-sm border-primary/10">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Estimates</CardTitle>
            <ClipboardList className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{isStatsLoading ? "..." : stats.total}</div>
            <p className="text-xs text-muted-foreground">Total requests generated by AI</p>
          </CardContent>
        </Card>
        <Card className="shadow-sm border-primary/10">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Interior Projects</CardTitle>
            <Paintbrush className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{isStatsLoading ? "..." : stats.interior}</div>
            <p className="text-xs text-muted-foreground">Jobs involving interior work</p>
          </CardContent>
        </Card>
        <Card className="shadow-sm border-primary/10">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Exterior Projects</CardTitle>
            <Home className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{isStatsLoading ? "..." : stats.exterior}</div>
            <p className="text-xs text-muted-foreground">Jobs involving exterior work</p>
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-sm">
        <CardHeader className="border-b bg-muted/30">
          <CardTitle>Recent Estimates</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <EstimatesTable />
        </CardContent>
      </Card>
    </div>
  );
}
